name: Email Step Action

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 22f1001861@ds.study.iitm.ac.in
        run: echo "Hello, world! This step is named after my email address."
