name: Cache Prime Example

on:
  workflow_dispatch:

jobs:
  prime_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: prime-cache-3e69df6
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache # Change to the path you want to cache (e.g., node_modules, ~/.cache, etc.)
          key: cache-3e69df6

      - name: Echo cache hit/miss
        run: |
          echo "Cache hit: ${{ steps.cache-step.outputs.cache-hit }}"
